package com.nsmall.api.status;

public enum OrderDetailStatus {
    CREATED, PRODUCT_READY, PRODUCT_SHORT, CANCELED, PAYMENT_SUCCEDED, PAYMENT_FAILED, SHIPMENT_PREPARING, SHIPMENT_FAILED, SHIPMENT_COMPLETED, FINISHED
}
