
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##NSMALL
    password: 1234
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none